
GRANT ALL PRIVILEGES ON DATABASE chatbot TO postgres;

CREATE SCHEMA IF NOT EXISTS public;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres; 